package comment

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// groupは "//" 行から1始まりで番号付けしたコメント群を作る。
func group(texts ...string) []commentLine {
	lines := make([]commentLine, len(texts))
	for i, t := range texts {
		lines[i] = commentLine{line: i + 1, text: t}
	}
	return lines
}

// sectionsOfはfindingsに含まれる節番号の一覧を返す。
func sectionsOf(fs []finding) []string {
	got := make([]string, len(fs))
	for i, f := range fs {
		got[i] = f.section
	}
	return got
}

func TestCheckGroup(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		lines        []commentLine
		wantSections []string
	}{
		{
			name:         "スタイルに従ったコメントは指摘しない",
			lines:        group("// 平文パスワードをbcryptでハッシュ化する。"),
			wantSections: nil,
		},
		{
			name:         "英数字と日本語の間のスペースを指摘する",
			lines:        group("// 平文パスワードを bcrypt でハッシュ化する。"),
			wantSections: []string{"3.2"},
		},
		{
			name:         "全角丸括弧を指摘する",
			lines:        group("// ユーザーIDを取得（削除済みユーザーは0を返す）。"),
			wantSections: []string{"3.1"},
		},
		{
			name:         "複数行のうち違反した行だけを指摘する",
			lines:        group("// 平文パスワードをハッシュ化する。", "//", "// cost は 10 を使う。"),
			wantSections: []string{"3.2"},
		},
		{
			name:         "1行が両方の節に違反したら2件指摘する",
			lines:        group("// フェーズ8-1（i18n キー命名規則）に対応する。"),
			wantSections: []string{"3.1", "3.2"},
		},
		{
			name:         "ブロックコメントの継続行も検査する",
			lines:        group("/*", " * 最大 20 文字まで入力できる。", " */"),
			wantSections: []string{"3.2"},
		},
		{
			name:         "インラインコードで囲んだ悪い例は指摘しない",
			lines:        group("// 悪い例は `最大 20 文字` のようにスペースを入れたもの。"),
			wantSections: nil,
		},
		{
			name:         "ツールへの指示は英数字だけなので指摘しない",
			lines:        group("//go:generate stringer -type=Season"),
			wantSections: nil,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			got := sectionsOf(checkGroup(tt.lines))
			if !equalStrings(got, tt.wantSections) {
				t.Errorf("checkGroupが検出した節番号 = %v、期待値 = %v", got, tt.wantSections)
			}
		})
	}
}

func TestCheckGroupReportsLineNumber(t *testing.T) {
	t.Parallel()

	lines := []commentLine{
		{line: 766, text: "// 最大 20 文字まで入力できる。"},
	}
	fs := checkGroup(lines)
	if len(fs) != 1 {
		t.Fatalf("違反数 = %d、期待値 = 1", len(fs))
	}
	if fs[0].line != 766 {
		t.Errorf("違反の行番号 = %d、期待値 = 766", fs[0].line)
	}
}

func TestCommentBody(t *testing.T) {
	t.Parallel()

	tests := []struct {
		text string
		want string
	}{
		{"// 本文", "本文"},
		{"//   字下げを保持する  ", "  字下げを保持する"},
		{"/* ブロックコメントの先頭", "ブロックコメントの先頭"},
		{"\t * 継続行", "継続行"},
		{"// ", ""},
	}
	for _, tt := range tests {
		if got := commentBody(tt.text); got != tt.want {
			t.Errorf("commentBody(%q) = %q、期待値 = %q", tt.text, got, tt.want)
		}
	}
}

func TestGoCommentGroupsIgnoresStringLiterals(t *testing.T) {
	t.Parallel()

	// 下の文字列リテラルはコメントとして抽出されてはならない。
	// さもないとツール自身のテストデータを誤検出する。
	src := []byte(strings.Join([]string{
		"package sample",
		"",
		"// Greetは挨拶を返す。",
		"func Greet() string {",
		"\treturn \"// 最大 20 文字\"",
		"}",
	}, "\n"))

	groups, err := goCommentGroups("sample.go", src)
	if err != nil {
		t.Fatalf("goCommentGroupsに失敗した: %v", err)
	}

	var lines int
	for _, g := range groups {
		lines += len(g)
	}
	if lines != 1 {
		t.Errorf("抽出したコメント行数 = %d、期待値 = 1 (文字列リテラルは無視する)", lines)
	}
}

func TestTemplCommentGroups(t *testing.T) {
	t.Parallel()

	// 行頭 "//" コメントの連続が非コメント行で区切られたら2群になり、
	// 末尾のマークアップはどの群にも含まれない。
	src := []byte(strings.Join([]string{
		"// 最初の群。",
		"// 2行目。",
		"templ Page() {",
		"\t<div>hello</div>",
		"// 2つ目の群。",
		"}",
	}, "\n"))

	groups := templCommentGroups(src)
	if len(groups) != 2 {
		t.Fatalf("コメント群の数 = %d、期待値 = 2", len(groups))
	}
	if groups[0][0].line != 1 {
		t.Errorf("最初の群の開始行 = %d、期待値 = 1", groups[0][0].line)
	}
	if groups[1][0].line != 5 {
		t.Errorf("2つ目の群の開始行 = %d、期待値 = 5", groups[1][0].line)
	}
}

func TestIsGenerated(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "定型の生成物ヘッダー",
			src:  "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage sample\n",
			want: true,
		},
		{
			name: "手書きのファイル",
			src:  "// Greetは挨拶を返す。\npackage sample\n",
			want: false,
		},
	}
	for _, tt := range tests {
		if got := isGenerated([]byte(tt.src)); got != tt.want {
			t.Errorf("%s: isGenerated = %v、期待値 = %v", tt.name, got, tt.want)
		}
	}
}

// TestRunReportsSpacingは一時ツリー上でサブコマンドを通しで動かし、§3.2の違反を
// stdoutに報告し、要約をstderrに書き、終了コード1を返すことを確認する。
func TestRunReportsSpacing(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "bad.go", strings.Join([]string{
		"package sample",
		"",
		"// 平文パスワードを bcrypt でハッシュ化する。",
		"func Bad() {}",
	}, "\n"))

	var stdout, stderr bytes.Buffer
	code := Run([]string{dir}, &stdout, &stderr)

	if code != 1 {
		t.Fatalf("終了コード = %d、期待値 = 1、標準エラー = %s", code, stderr.String())
	}
	if !strings.Contains(stdout.String(), "bad.go:3:") {
		t.Errorf("標準出力 = %q、bad.go:3の違反を期待", stdout.String())
	}
	if !strings.Contains(stdout.String(), "§3.2") {
		t.Errorf("標準出力 = %q、節番号を含むことを期待", stdout.String())
	}
	if !strings.Contains(stderr.String(), "日本語スタイル違反1件") {
		t.Errorf("標準エラー = %q、違反の要約を含むことを期待", stderr.String())
	}
}

// TestRunReportsFullWidthParenは §3.1の違反をツリー全体で報告することを確認する。
func TestRunReportsFullWidthParen(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "bad.go", strings.Join([]string{
		"package sample",
		"",
		"// ユーザーIDを取得（削除済みユーザーは0を返す）。",
		"func Bad() {}",
	}, "\n"))

	var stdout, stderr bytes.Buffer
	code := Run([]string{dir}, &stdout, &stderr)

	if code != 1 {
		t.Fatalf("終了コード = %d、期待値 = 1、標準エラー = %s", code, stderr.String())
	}
	if !strings.Contains(stdout.String(), "bad.go:3:") {
		t.Errorf("標準出力 = %q、bad.go:3の違反を期待", stdout.String())
	}
	if !strings.Contains(stdout.String(), "§3.1") {
		t.Errorf("標準出力 = %q、節番号を含むことを期待", stdout.String())
	}
}

// TestRunChecksTemplFilesは .templファイルのコメントも検査対象になることを確認する。
func TestRunChecksTemplFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "page.templ", strings.Join([]string{
		"package templates",
		"",
		"// Page は 1 ページ分のマークアップを返す。",
		"templ Page() {",
		"\t<div>hello</div>",
		"}",
	}, "\n"))

	var stdout, stderr bytes.Buffer
	code := Run([]string{dir}, &stdout, &stderr)

	if code != 1 {
		t.Fatalf("終了コード = %d、期待値 = 1、標準エラー = %s", code, stderr.String())
	}
	if !strings.Contains(stdout.String(), "page.templ:3:") {
		t.Errorf("標準出力 = %q、page.templ:3の違反を期待", stdout.String())
	}
}

// TestRunNoViolationsは問題のないツリーが無出力・終了コード0になることを確認する。
func TestRunNoViolations(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "good.go", strings.Join([]string{
		"package sample",
		"",
		"// Greetは挨拶を返す。",
		"// 最大20文字まで返す (それ以上は切り詰める)。",
		"func Greet() string { return \"hi\" }",
		"",
		"// Waveはユーザーに手を振る。",
		"// 詳細は https://example.com/wave を参照する。",
		"func Wave() {}",
	}, "\n"))

	var stdout, stderr bytes.Buffer
	code := Run([]string{dir}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("終了コード = %d、期待値 = 0、標準出力 = %s、標準エラー = %s", code, stdout.String(), stderr.String())
	}
	if stdout.String() != "" {
		t.Errorf("標準出力 = %q、空を期待", stdout.String())
	}
}

// TestRunSkipsGeneratedFilesは、生成物が違反を含んでいても検査対象外になることを
// 確認する。
func TestRunSkipsGeneratedFiles(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "gen.go", strings.Join([]string{
		"// Code generated by stringer. DO NOT EDIT.",
		"package sample",
		"",
		"// 最大 20 文字まで入力できる。",
		"func Gen() {}",
	}, "\n"))

	var stdout, stderr bytes.Buffer
	code := Run([]string{dir}, &stdout, &stderr)

	if code != 0 {
		t.Fatalf("終了コード = %d、期待値 = 0 (生成物はスキップする)、標準出力 = %s", code, stdout.String())
	}
}

// TestRunHelpExitsZeroは -h要求が成功扱いになることを確認する。
func TestRunHelpExitsZero(t *testing.T) {
	t.Parallel()

	var stdout, stderr bytes.Buffer
	if code := Run([]string{"-h"}, &stdout, &stderr); code != 0 {
		t.Errorf("Run(-h) の終了コード = %d、期待値 = 0", code)
	}
}

// writeFileはdir配下のnameにcontentを書き出し、失敗時にテストを止める。
func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
		t.Fatalf("%sの書き込みに失敗した: %v", name, err)
	}
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func TestRunExcludesCodeAndDirectives(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		comments []string
	}{
		{name: "タブでインデントしたコード", comments: []string{"// コード例。", "//", "//\tfmt.Println(\"最大 20 文字（例）\")"}},
		{name: "スペースでインデントしたコード", comments: []string{"// コード例。", "//", "//     fmt.Println(\"最大 20 文字（例）\")"}},
		{name: "バッククォートのフェンス", comments: []string{"// ```go", "// fmt.Println(\"最大 20 文字（例）\")", "// ```"}},
		{name: "チルダのフェンス", comments: []string{"// ~~~go", "// fmt.Println(\"最大 20 文字（例）\")", "// ~~~~"}},
		{name: "短いフェンスでは閉じない", comments: []string{"// ````go", "// ```", "// 最大 20 文字（例）", "// ~~~~", "// 最大 20 文字（例）", "// ````"}},
		{name: "末尾に本文があるフェンスでは閉じない", comments: []string{"// ```go", "// ``` 最大 20 文字（例）", "// 最大 20 文字（例）", "// ```"}},
		{name: "星付きブロックコメント", comments: []string{"/*", " * コード例。", " *", " *\tfmt.Println(\"最大 20 文字（例）\")", " */"}},
		{name: "ブロックコメントの共通インデント", comments: []string{"/*", "\tコード例。", "", "\t\tfmt.Println(\"最大 20 文字（例）\")", "*/"}},
		{name: "箇条書きが字下げのない行で終わればコード例に戻る", comments: []string{"// 項目。", "//", "//   - 項目1。", "//", "// 通常の段落。", "//", "//\tfmt.Println(\"最大 20 文字（例）\")"}},
		{name: "日本語引数の生成指示", comments: []string{"//go:generate echo 最大 20 文字（例）"}},
		{name: "リンタへの指示", comments: []string{"//nolint:unused // 最大 20 文字（例）", "//lint:ignore U1000 最大 20 文字（例）", "//nolint // 最大 20 文字（例）"}},
	}
	for _, tt := range tests {
		for _, ext := range []string{".go", ".templ"} {
			if ext == ".templ" && strings.HasPrefix(tt.comments[0], "/*") {
				continue
			}
			t.Run(tt.name+ext, func(t *testing.T) {
				t.Parallel()
				dir := t.TempDir()
				before := "// 前は最大 20 文字（例）"
				after := "// 後は最大 20 文字（例）"
				lines := append([]string{"package sample", before}, tt.comments...)
				lines = append(lines, after)
				writeFile(t, dir, "sample"+ext, strings.Join(lines, "\n"))
				var stdout, stderr bytes.Buffer
				if code := Run([]string{dir}, &stdout, &stderr); code != 1 {
					t.Fatalf("終了コード = %d、期待値 = 1、標準エラー = %s", code, stderr.String())
				}
				path := filepath.Join(dir, "sample"+ext)
				want := []string{
					fmt.Sprintf("%s:2: §3.1", path), fmt.Sprintf("%s:2: §3.2", path),
					fmt.Sprintf("%s:%d: §3.1", path, len(lines)), fmt.Sprintf("%s:%d: §3.2", path, len(lines)),
				}
				got := strings.Split(strings.TrimSpace(stdout.String()), "\n")
				if len(got) != len(want) {
					t.Fatalf("報告行数 = %d、期待値 = %d\n%s", len(got), len(want), stdout.String())
				}
				for i := range want {
					if !strings.HasPrefix(got[i], want[i]) {
						t.Errorf("報告 = %q、期待する接頭辞 = %q", got[i], want[i])
					}
				}
			})
		}
	}
}

func TestCheckGroupKeepsProse(t *testing.T) {
	t.Parallel()

	for _, tt := range []struct {
		name     string
		lines    []commentLine
		wantLine int
	}{
		{name: "ブロック本文の共通インデントはコードとみなさない", lines: group("/*", "\t最大 20 文字（例）", "*/"), wantLine: 2},
		{name: "空白付きの指示名は地の文", lines: group("// go:generateは最大 20 文字（例）"), wantLine: 1},
		{name: "nolintで始まる別の単語は地の文", lines: group("//nolinter 最大 20 文字（例）"), wantLine: 1},
		{name: "字下げされた箇条書きは地の文", lines: group("// 項目。", "//", "//   - 最大 20 文字（例）"), wantLine: 3},
		{name: "箇条書きの折り返しは地の文", lines: group("// 項目。", "//", "//   1. 説明。", "//      最大 20 文字（例）"), wantLine: 4},
		{name: "空行を挟んだ箇条書きの2段落目は地の文", lines: group("// 項目。", "//", "//   - 項目1。", "//", "//     最大 20 文字（例）"), wantLine: 5},
		{name: "箇条書きの中はタブ字下げでも地の文", lines: group("// 項目。", "//", "//   - 項目1。", "//", "//\t最大 20 文字（例）"), wantLine: 5},
		{name: "フェンスを含むインラインコードは後ろを隠さない", lines: group("// ```正常```", "// 最大 20 文字（例）"), wantLine: 2},
	} {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := checkGroup(tt.lines)
			if len(got) != 2 {
				t.Fatalf("違反数 = %d、期待値 = 2", len(got))
			}
			for _, f := range got {
				if f.line != tt.wantLine {
					t.Errorf("行番号 = %d、期待値 = %d", f.line, tt.wantLine)
				}
			}
		})
	}
}

func TestRunFenceDoesNotLeakBetweenGroups(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	writeFile(t, dir, "sample.go", strings.Join([]string{
		"package sample", "// ```go", "// 最大 20 文字（例）", "func Example() {}",
		"// 最大 20 文字（例）", "func After() {}",
	}, "\n"))
	var stdout, stderr bytes.Buffer
	if code := Run([]string{dir}, &stdout, &stderr); code != 1 {
		t.Fatalf("終了コード = %d、期待値 = 1", code)
	}
	if strings.Count(stdout.String(), "sample.go:5:") != 2 || strings.Count(stdout.String(), "\n") != 2 {
		t.Errorf("次のコメント群の2件だけを期待したが、出力は %q", stdout.String())
	}
}

// TestRunDiffModeLimitsToAddedLinesは -base=<ref> が <ref> 以降に追加された行だけを
// 報告することを、一時的なGitリポジトリで確認する。
// 既存行の違反は残したまま新しい違反を足し、追加行だけが報告される形にしている。
func TestRunDiffModeLimitsToAddedLines(t *testing.T) {
	// addedLinesは作業ディレクトリのGitリポジトリを見るため、t.Chdirで一時リポジトリへ移る。
	// t.Chdirはプロセス全体に効くため、このテストはt.Parallelを使えない。
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("gitが無いため差分モードを検査できない")
	}

	dir := t.TempDir()
	git := func(args ...string) {
		t.Helper()
		// argsはこのテストが渡すリテラルだけで、外部入力は混ざらない。
		// gosecのコマンド混入警告 (G204) はここでは当てはまらない。
		cmd := exec.Command("git", args...) //#nosec G204
		cmd.Dir = dir
		cmd.Env = append(os.Environ(),
			"GIT_AUTHOR_NAME=t", "GIT_AUTHOR_EMAIL=t@example.com",
			"GIT_COMMITTER_NAME=t", "GIT_COMMITTER_EMAIL=t@example.com",
		)
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %sに失敗した: %v: %s", strings.Join(args, " "), err, out)
		}
	}

	git("init", "-q", "-b", "main")
	writeFile(t, dir, "sample.go", strings.Join([]string{
		"package sample", "", "// 既存の 最大 20 文字。", "func A() {}",
	}, "\n"))
	git("add", "-A")
	git("commit", "-qm", "base")

	writeFile(t, dir, "sample.go", strings.Join([]string{
		"package sample", "", "// 既存の 最大 20 文字。", "func A() {}", "",
		"// 追加の 最大 20 文字。", "func B() {}",
	}, "\n"))
	git("add", "-A")
	git("commit", "-qm", "next")

	t.Chdir(dir)

	var stdout, stderr bytes.Buffer
	if code := Run([]string{"-base=HEAD~1", "."}, &stdout, &stderr); code != 1 {
		t.Fatalf("終了コード = %d、期待値 = 1、標準エラー = %s", code, stderr.String())
	}
	got := strings.TrimSpace(stdout.String())
	if strings.Count(got, "\n") != 0 || !strings.Contains(got, "sample.go:6:") {
		t.Errorf("標準出力 = %q、追加行 sample.go:6 の1件だけを期待", got)
	}
}
