package comment

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
	"testing"
)

// TestRunSyntaxは本文の違反と構文の除外を、CLIの診断位置・件数まで含めて確認する。
func TestRunSyntax(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		ext  string
		src  string
		want []string
	}{
		{name: "シェルのコマンドと引数の区切り", ext: ".sh", src: "echo 処理が完了しました\n"},
		{name: "シェルのコマンド名と引数の区切り", ext: ".sh", src: "cmd1 完了しました\n"},
		{name: "シェルの引用符なし引数の本文", ext: ".sh", src: "echo 完了 20 件\n", want: []string{"1: §3.2"}},
		{name: "シェルの引用符なし引数の全角丸括弧", ext: ".sh", src: "echo 最大 20 文字（入力）\n", want: []string{"1: §3.1", "1: §3.2"}},
		{name: "シェルのオプションと引数の区切り", ext: ".sh", src: "find . -name 日本語\n"},
		{name: "シェルの引用符なし引数の展開式", ext: ".sh", src: "echo 完了 $COUNT 件\n"},
		{name: "シェルの引用符なし引数の行継続", ext: ".sh", src: "echo 正常 \\\n  最大 20 文字\n", want: []string{"2: §3.2"}},
		{name: "シェルの二重引用符の本文", ext: ".sh", src: "echo \"最大 20 文字（入力）\"\n", want: []string{"1: §3.1", "1: §3.2"}},
		{name: "シェルの単一引用符の本文", ext: ".sh", src: "echo '最大 20 文字'\n", want: []string{"1: §3.2"}},
		{name: "シェルのANSI引用符の本文", ext: ".sh", src: "echo $'最大 20 文字'\n", want: []string{"1: §3.2"}},
		{name: "シェルの複数行文字列", ext: ".sh", src: "echo \"\n最大 20 文字\n\"\n", want: []string{"2: §3.2"}},
		{name: "シェルの引用されたバッククォートは本文", ext: ".sh", src: "echo '`最大 20 文字`'\n", want: []string{"1: §3.2"}},
		{name: "シェルのコメント内のインラインコード", ext: ".sh", src: "# 例は `最大 20 文字（入力）`\necho 完了\n"},
		{name: "シェルのコメント本文", ext: ".sh", src: "echo 完了 # 最大 20 文字\n", want: []string{"1: §3.2"}},
		{name: "シェルの引数中のコメント記号", ext: ".sh", src: "echo \"# 最大 20 文字\"\n", want: []string{"1: §3.2"}},
		{name: "シェルの展開式と本文を分離", ext: ".sh", src: "echo \"${LIMIT} 件まで\"\n"},
		{name: "シェルの展開式の前後の本文", ext: ".sh", src: "echo \"最大 20 文字 ${LIMIT} 最大 30 文字\"\n", want: []string{"1: §3.2"}},
		{name: "シェルのコマンド置換内の引数", ext: ".sh", src: "echo \"$(printf '%s' '最大 20 文字')\"\n", want: []string{"1: §3.2"}},
		{name: "シェルのヒアドキュメント", ext: ".sh", src: "cat <<EOF\n最大 20 文字 ${LIMIT} まで\nEOF\n", want: []string{"2: §3.2"}},
		{name: "シェルの引用されたヒアドキュメント", ext: ".sh", src: "cat <<'EOF'\n`最大 20 文字`\nEOF\n", want: []string{"2: §3.2"}},
		{name: "通常のTypeScript文字列", ext: ".ts", src: "const label: string = \"最大 20 文字（入力）\";\n", want: []string{"1: §3.1", "1: §3.2"}},
		{name: "単一行テンプレートの本文", ext: ".ts", src: "const label = `最大 20 文字（入力）`;\n", want: []string{"1: §3.1", "1: §3.2"}},
		{name: "複数行テンプレートの本文", ext: ".ts", src: "const label = `\n最大 20 文字（入力）\n`;\n", want: []string{"2: §3.1", "2: §3.2"}},
		{name: "TypeScriptの単一引用符の本文", ext: ".ts", src: "const label = '最大 20 文字';\n", want: []string{"1: §3.2"}},
		{name: "TypeScript文字列内のバッククォートは本文", ext: ".ts", src: "const label = '`最大 20 文字`';\n", want: []string{"1: §3.2"}},
		{name: "TypeScriptのコメント内のインラインコード", ext: ".ts", src: "// 例は `最大 20 文字（入力）`\nconst label = '正常';\n"},
		{name: "TypeScriptのブロックコメント", ext: ".ts", src: "/**\n * 最大 20 文字\n * 例は `最大 20 文字`\n */\n", want: []string{"2: §3.2"}},
		{name: "TypeScriptの文字列と行末コメント", ext: ".ts", src: "const label = '最大 20 文字'; // 最大 30 文字\n", want: []string{"1: §3.2"}},
		{name: "TypeScriptの引用符エスケープ", ext: ".ts", src: "const label = \"引用\\\"最大 20 文字\";\n", want: []string{"1: §3.2"}},
		{name: "TypeScriptの補間式と本文を分離", ext: ".ts", src: "const label = `件数${n + 1} 件`;\n"},
		{name: "TypeScriptの補間式の前後の本文", ext: ".ts", src: "const label = `最大 20 文字 ${n + 1} 最大 30 文字`;\n", want: []string{"1: §3.2"}},
		{name: "TypeScriptの複数行補間後の行番号", ext: ".ts", src: "const label = `正常${\n n + 1\n}最大 20 文字`;\n", want: []string{"3: §3.2"}},
		{name: "TypeScriptの入れ子の補間", ext: ".ts", src: "const label = `正常${flag ? `最大 20 文字${n}` : '正常'}`;\n", want: []string{"1: §3.2"}},
		{name: "TypeScriptの正規表現は構文", ext: ".ts", src: "const pattern = /最大 20 文字（入力）/;\nconst label = `最大 20 文字`;\n", want: []string{"2: §3.2"}},
		{name: "TypeScriptの文字列内のコメント記号", ext: ".ts", src: "const label = `// 最大 20 文字`;\n", want: []string{"1: §3.2"}},
		{name: "TypeScriptのCRLFと日本語の行番号", ext: ".ts", src: "const label = `正常\r\n最大 20 文字\r\n`;\r\n", want: []string{"2: §3.2"}},
		{name: "TypeScriptのURLを除外", ext: ".ts", src: "const label = `https://example.com/ で配信している`;\n"},
		{name: "TypeScriptの生成物を除外", ext: ".ts", src: "// Code generated by tool. DO NOT EDIT.\nconst label = `最大 20 文字`;\n"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()
			name := "sample" + tt.ext
			writeFile(t, dir, name, tt.src)
			var stdout, stderr bytes.Buffer
			code := Run([]string{dir}, &stdout, &stderr)
			wantCode := 0
			wantStderr := ""
			if len(tt.want) > 0 {
				wantCode = 1
				wantStderr = fmt.Sprintf("\nkoryluslint comment: 日本語スタイル違反%d件\n", len(tt.want))
			}
			if code != wantCode || stderr.String() != wantStderr {
				t.Fatalf("終了コード = %d、期待値 = %d、標準エラー = %q、期待値 = %q", code, wantCode, stderr.String(), wantStderr)
			}
			var lines []string
			if stdout.Len() > 0 {
				lines = strings.Split(strings.TrimSpace(stdout.String()), "\n")
			}
			if len(lines) != len(tt.want) {
				t.Fatalf("診断数 = %d、期待値 = %d、標準出力 = %q", len(lines), len(tt.want), stdout.String())
			}
			for i, want := range tt.want {
				prefix := filepath.Join(dir, name) + ":" + want + ":"
				if !strings.HasPrefix(lines[i], prefix) {
					t.Errorf("診断 = %q、期待する接頭辞 = %q", lines[i], prefix)
				}
			}
		})
	}
}

// TestRunSyntaxErrorsは抽出できないファイルを既存の解析エラーと同様に通知することを確認する。
func TestRunSyntaxErrors(t *testing.T) {
	t.Parallel()
	for _, tt := range []struct {
		ext string
		src string
	}{
		{ext: ".sh", src: "echo \"最大 20 文字\n"},
		{ext: ".ts", src: "const label = `最大 20 文字\n"},
	} {
		t.Run(tt.ext, func(t *testing.T) {
			t.Parallel()
			dir := t.TempDir()
			writeFile(t, dir, "sample"+tt.ext, tt.src)
			var stdout, stderr bytes.Buffer
			if code := Run([]string{dir}, &stdout, &stderr); code != 0 {
				t.Fatalf("終了コード = %d、期待値 = 0", code)
			}
			if stdout.Len() != 0 || !strings.Contains(stderr.String(), "構文エラー") {
				t.Errorf("標準出力 = %q、標準エラー = %q、解析エラーだけの通知を期待", stdout.String(), stderr.String())
			}
		})
	}
}
